Task completed
Sergey-Shar/tms_react pull request #11
Opened 2021-12-09 09:45 UTC by Sergey-Shar

2021-12-12 14:28 UTC, NearFutureBand requested changes

2021-12-12 14:28 UTC, NearFutureBand commented on src/components/ButtonsPanation/index.js
> +const Button = (number) => {
Если это компонент, то входные параметры нужно оформлять как props - за пример можно взять домашку по пропсам, когда мы делали текст с разными цветами, шрифтом и подчеркнутый / не подчеркнутый. Если посмотреть на то как принимались пропсы в той дз, то там будет написано что-то вроде `const Component = ({ size, color, text , ... }) => { `.  Поэтому здесь нужно поступить также - ({ number })

2021-12-12 14:28 UTC, NearFutureBand commented on src/components/Pagination/index.js
> +            {image.length && Button(setPagination)}
Собственные компоненты вызываются не как функции (хотя это работает), а как тэги. То есть `<Button />`

2021-12-12 14:28 UTC, NearFutureBand commented on src/components/Pagination/index.js
> +            {image.length && Button(setPagination)}
И setPagination нужно передать как проп в компонент Button. И согласно изменениям в самом первом комментарии у компонента Button теперь есть проп который называется number.

2021-12-12 14:28 UTC, NearFutureBand commented on src/components/Pagination/index.js
> +            {image.length && Button(setPagination)}
Чтобы это все записать, лучше использовать домашку (Р-5) по пропсам как пример

2021-12-14 11:30 UTC, NearFutureBand approved these changes
Аппрув + два комментария, не требующих измненения

2021-12-14 11:30 UTC, NearFutureBand commented on src/components/Pagination/index.js
> +            {image.length ? image.map(img => {
Можно не проверять на длину, если массив image пустой, то map не упадет с ошибкой

2021-12-14 11:30 UTC, NearFutureBand commented on src/components/Pagination/index.js
> +            {image.length && <Button numbers = {setPagination}/>}
Тут все верно теперь, единственное на что в будущем стоит обращать внимание - на названия переменных, нужно чтобы их имена говорили о том что они такое и для чего нужны. То есть проп называется numbers и в него передается функция. Тут можно и имя пропа задать такое же. Потому что setPagination - судя по названию это явно функция, которая меняет чье-то значение, а название numbers - никак не говорит что это функция которая делает что-то подобное. Внутри компонента Button переменная numbers которая на самом деле функция выглядит еще страннее. Но это совет на будущее, текущая задача решена правильно, поэтому аппрув.

2021-12-15 07:05 UTC, Sergey-Shar commented on src/components/Pagination/index.js
> +            {image.length ? image.map(img => {
учел👍

2021-12-15 07:05 UTC, Sergey-Shar commented on src/components/Pagination/index.js
> +            {image.length && <Button numbers = {setPagination}/>}
спасибо

2021-12-15 11:26 UTC, merged