Task names click
Sergey-Shar/tms_react pull request #15
Opened 2021-12-16 12:30 UTC by Sergey-Shar

2021-12-19 15:49 UTC, NearFutureBand requested changes

2021-12-19 15:49 UTC, NearFutureBand commented on src/components/Names/index.js
> +                    <div className="names" key={index}>{name}</div>
Лучше не использовать it (который index из map) в качестве key. Нужно чтобы каждый элемент всегда имел один и тот же ключ, при любом количестве перерисовок и при любых манипуляциях со списком (перестановка / удаление элементов). При перестановке элементов списка ключи бы перерассчитались, если использовать index из map в качестве key. Лучше передать какое-нибудь уникальное значение которое уже есть в массиве. Это также может быть сам элемент массива

2021-12-20 10:09 UTC, Sergey-Shar commented on src/components/Names/index.js
> +                    <div className="names" key={index}>{name}</div>
Повторение, мать учения) Ты об этом говорил, хорошо что в этом кейсе закрепили, теперь точно запомню)

2021-12-20 11:29 UTC, NearFutureBand approved these changes

2021-12-20 13:41 UTC, merged