Task is ready for review
Sergey-Shar/tms_react pull request #17
Opened 2021-12-17 20:56 UTC by Sergey-Shar

2021-12-19 16:49 UTC, NearFutureBand requested changes
Отличное крутое решение, главная часть выполнена и работает - есть только пара небольших косяков - key в двух местах и на видосе-результате по умолчанию при клике на 1 - показывается красный квадрат, но это не критично.

2021-12-19 16:49 UTC, NearFutureBand commented on src/components/Figure/index.js
> +    }, [params.id])
Можно стейт и эффект не создавать, а сразу использовать params.id

2021-12-19 16:49 UTC, NearFutureBand commented on src/components/Navbar/index.js
> +                        <button key={index}
index в key

2021-12-19 16:49 UTC, NearFutureBand commented on src/components/Navbar/index.js
> +                        <button key={index}
index в key

2021-12-20 14:52 UTC, NearFutureBand approved these changes

2021-12-20 14:52 UTC, NearFutureBand commented on src/components/Figure/index.js
> +    }, [params.id])
Это замечание если здесь решил не исправлять, то на будущее обязательно надо запомнить и лишний стейт не создавать. Стейт здесь имел бы место, если бы была задача как-то кликать на саму фигуру и она бы меняла свою форму. То есть логика изменения формы была бы тогда внутри компонента фигуры. А в данном случае не так - компоненту Figure сообщается извне какой ей быть, поэтому точно не стейт.

2021-12-21 07:12 UTC, Sergey-Shar commented on src/components/Figure/index.js
> +    }, [params.id])
Я просто не успевал вчера) Сейчас все переделаю, спасибо за  фитбэк 👍

2021-12-21 07:18 UTC, Sergey-Shar commented on src/components/Figure/index.js
> +    }, [params.id])
тут просто идея в том была, что в зависимости от айди менялся класснейм и отображалась нужная фигура и текст внутри, переменная стэйта за это и отвечала.

2021-12-21 07:38 UTC, merged