'task completed'
Sergey-Shar/tms_react pull request #3
Opened 2021-11-30 09:53 UTC by Sergey-Shar

<img width="1021" alt="Снимок экрана 2021-11-30 в 12 51 48" src="https://user-images.githubusercontent.com/86597028/144025022-8b7c8377-f937-4a37-9757-56d6cdc6dcca.png">

2021-12-01 14:45 UTC, NearFutureBand requested changes
Все супер, только один момент по способу задания стилей

2021-12-01 14:45 UTC, NearFutureBand commented on src/components/UserList/index.js
> +            <div key={item._id} style={{textAlign:'center',border:'solid 1px',margin:'10px auto', width: '50%'}} >'
Стили, которые не зависят ни от каких переменных, выносятся в css файл

2021-12-02 09:49 UTC, Sergey-Shar commented on src/components/UserList/index.js
> +            <div key={item._id} style={{textAlign:'center',border:'solid 1px',margin:'10px auto', width: '50%'}} >'
Исправил.

2021-12-02 20:51 UTC, NearFutureBand approved these changes
Все супер

2021-12-03 06:55 UTC, merged